import type { Metadata } from "next";
import { Exo, Jersey_20_Charted } from "next/font/google";
import "./globals.scss";

const exo = Exo({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className + "font-normal"}>{children}</body>
    </html>
  );
}
